# Generated by Django 4.0.5 on 2022-07-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stock_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stock'),
        ),
    ]
