# Generated by Django 4.0.5 on 2022-07-01 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='amount_in_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
