# Generated by Django 4.0.5 on 2022-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("products", "0002_alter_product_price"), ("orders", "0005_stock_stock_products")]

    operations = [migrations.AlterUniqueTogether(name="productstock", unique_together={("product", "stock")})]
