# Generated by Django 4.0.5 on 2022-07-01 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)]),
        )
    ]
